### ISSUE TITLE
[CI/CD] - Docker container for the server and e2e tests 

### ISSUE THREAD

**Issue by Bandisa** [Bandisa/fullstackclj#7]
# Tasks
- [x] Docker container for the server
- [x] Docker container for e2e tests
- [ ] Update github workflows for all tests

**Comment by Bandisa** [comment]
Yet to write e2e tests, will open a seperate issue since I am not certain about the best tool for the job, in the context of clojure.
